/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.hangingtest

import io.temporal.api.common.v1.WorkflowExecution
import io.temporal.client.WorkflowClient
import io.temporal.client.WorkflowOptions
import java.util.*


const val TASK_QUEUE = "HelloActivityTaskQueue"

class Starter(private val client: WorkflowClient) {
    private fun workflowStub() = WorkflowOptions {
        setWorkflowId("WORKFLOW_ID_${UUID.randomUUID()}")
        setTaskQueue(TASK_QUEUE)
    }.let { wo ->
        client.newWorkflowStub(
            GreetingWorkflow::class.java, wo
        )
    }

    fun spawn(arg: String): WorkflowExecution = WorkflowClient.start(workflowStub()::greeting, arg)

    fun getResult(handle: WorkflowExecution): String =
        client.newUntypedWorkflowStub(handle.workflowId).getResult(String::class.java)
}

fun starter() {
    val starter = Starter(client())

    while (true) {
        val arg = "Thadani  ${UUID.randomUUID()}"
        starter.spawn(arg)
        println("Created ${arg}")
        Thread.sleep(15000)
    }
}




